# Generated by Django 5.0.1 on 2024-03-23 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.TextField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('podcast', models.TextField()),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('audio', 'audio'), ('video', 'video')], default='audio', max_length=255)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(default=0, related_name='podcast_likes', to='api.user')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
    ]
