# Generated by Django 5.0.1 on 2024-03-02 19:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cover_image', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('content', models.TextField(blank=True, null=True)),
                ('likes', models.ManyToManyField(related_name='blog_likes', to='api.user')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
    ]
