# Generated by Django 5.0.1 on 2024-03-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='creation_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
