# Generated by Django 5.0.1 on 2024-03-06 10:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.TextField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
